import { createServiceClient } from "@/lib/supabase/server";
import { fetchTeams } from "@/lib/api/football-data";

const DUTCH_NAMES: Record<string, string> = {
  "Germany": "Duitsland",
  "Spain": "Spanje",
  "France": "Frankrijk",
  "Brazil": "Brazilië",
  "Argentina": "Argentinië",
  "Portugal": "Portugal",
  "Netherlands": "Nederland",
  "England": "Engeland",
  "Belgium": "België",
  "Italy": "Italië",
  "Croatia": "Kroatië",
  "Switzerland": "Zwitserland",
  "Denmark": "Denemarken",
  "Sweden": "Zweden",
  "Norway": "Noorwegen",
  "Poland": "Polen",
  "Austria": "Oostenrijk",
  "Czech Republic": "Tsjechië",
  "Czechia": "Tsjechië",
  "Slovakia": "Slowakije",
  "Slovenia": "Slovenië",
  "Hungary": "Hongarije",
  "Romania": "Roemenië",
  "Bulgaria": "Bulgarije",
  "Serbia": "Servië",
  "Greece": "Griekenland",
  "Turkey": "Turkije",
  "Russia": "Rusland",
  "Ukraine": "Oekraïne",
  "Scotland": "Schotland",
  "Wales": "Wales",
  "Ireland": "Ierland",
  "Northern Ireland": "Noord-Ierland",
  "Albania": "Albanië",
  "Morocco": "Marokko",
  "Senegal": "Senegal",
  "Ghana": "Ghana",
  "Nigeria": "Nigeria",
  "Cameroon": "Kameroen",
  "Egypt": "Egypte",
  "Tunisia": "Tunesië",
  "Algeria": "Algerije",
  "Ivory Coast": "Ivoorkust",
  "South Africa": "Zuid-Afrika",
  "USA": "Verenigde Staten",
  "United States": "Verenigde Staten",
  "Mexico": "Mexico",
  "Canada": "Canada",
  "Ecuador": "Ecuador",
  "Colombia": "Colombia",
  "Chile": "Chili",
  "Peru": "Peru",
  "Uruguay": "Uruguay",
  "Paraguay": "Paraguay",
  "Bolivia": "Bolivia",
  "Venezuela": "Venezuela",
  "Japan": "Japan",
  "South Korea": "Zuid-Korea",
  "Korea Republic": "Zuid-Korea",
  "Australia": "Australië",
  "Iran": "Iran",
  "Saudi Arabia": "Saoedi-Arabië",
  "Qatar": "Qatar",
  "China PR": "China",
  "China": "China",
  "Indonesia": "Indonesië",
  "New Zealand": "Nieuw-Zeeland",
  "Costa Rica": "Costa Rica",
  "Panama": "Panama",
  "Honduras": "Honduras",
  "Guatemala": "Guatemala",
  "Jamaica": "Jamaica",
  "Trinidad and Tobago": "Trinidad en Tobago",
  "Curaçao": "Curaçao",
  "Bosnia and Herzegovina": "Bosnië-Herzegovina",
  "North Macedonia": "Noord-Macedonië",
  "Montenegro": "Montenegro",
  "Georgia": "Georgië",
  "Iceland": "IJsland",
  "Finland": "Finland",
  "Lithuania": "Litouwen",
  "Latvia": "Letland",
  "Estonia": "Estland",
  "Luxembourg": "Luxemburg",
  "Malta": "Malta",
  "Cyprus": "Cyprus",
  "Kosovo": "Kosovo",
  "Faroe Islands": "Faeröer",
  "Angola": "Angola",
  "Cape Verde": "Kaapverdië",
  "Mozambique": "Mozambique",
  "Tanzania": "Tanzania",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabwe",
};

export async function syncTeams(competitionId?: string): Promise<{ processed: number }> {
  const supabase = await createServiceClient();
  const teams = await fetchTeams(competitionId);

  let processed = 0;
  for (const team of teams) {
    const { error } = await supabase.from("teams").upsert(
      {
        external_id: String(team.id),
        name: DUTCH_NAMES[team.name] ?? team.name,
        short_name: team.shortName,
        tla: team.tla,
        flag_url: team.crest,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "external_id" }
    );
    if (!error) processed++;
  }

  return { processed };
}
